### PR TITLE
Setup cra

### PR DESCRIPTION
**Pull request by enocol**
project initiallised with CRA
react-redux, react-router and reactjs toolkit installed

### CODE REVIEW

**Comment by enocol** [comment]
Hi King, Please review the changes I have made in this pull request so that we could proceed. I have created the development branch call dev. This branch need to be made the default branch, I tried doing that but seems I dont have  the right permission. Also,please I think a licence has to be added to the project as well. Thank you.

**Comment by Kingno3l** [comment]
## Status: Approved :heavy_check_mark:

Hi @enocol 

Your project is complete! Great job 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Installed react-router, react-redux, and redux toolkit

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Munsa1** [comment]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Munsa1** [comment]
Please note that I made a mistake the student used GitHub Flow instead of Gitflow. For peer-to-peer reviews between yourselves, you will need to use GitFlow e.g

`request to merge into development from a feature branch`

Then when you are about to ask for a final review of the project, you will request to `merge into main from the development branch`

Checkout these step by step guidelines on how to work on your project [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md)

**Pull request merged**
